import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import styles from "./page.module.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meli Challenge App - Next.js",
  description: "Generated by my",
  icons: {
    icon: './icon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
