import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import styles from "./page.module.scss"

//Add suspense to the root layout to use UseSearchParams from next.js
import { Suspense } from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meli Challenge App - Next.js",
  description: "Generated by my",
  icons: {
    icon: './icon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Suspense>
          <Header />
          <main className={styles.main}>
            {children}
          </main>
        </Suspense>
      </body>
    </html>
  );
}
